language: python

python:
    - 2.7

env:
    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py27-django16 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py27-django17 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py27-django18 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py34-django15
    - TOXENV=py34-django16 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py34-django17 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py34-django18 DJANGO_SELENIUM_TESTS=1

install:
    - pip install tox 

script:
    - tox

sudo: false
